### ISSUE TITLE
Not Using Secret Management

### ISSUE THREAD

**Issue by djbehnke** [jhdis/Snipe-IT-Reporting#1]
I was checking this repo out and saw that you were storing credentials inside your scripts in plain text. It's usually best practices to store those credentials as secrets with some sort of secret management system. It looks like one exists in powershell. Maybe look into implementing this to level up your security practices:

https://github.com/PowerShell/SecretManagement

It will also make it easier to push changes to the repo here since you don't need to worry about removing the credentials in order to push.

**Comment by jhdis** [comment]
Secret management has been implemented for the API token!
